version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "feat(rust)"
    groups:
      config-disassembler:
        patterns:
          - "config-disassembler"
      cargo:
        patterns:
          - "*"
        exclude-patterns:
          - "config-disassembler"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(dev-deps)"
    groups:
      dev-dependencies:
        dependency-type: "development"
