import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["test/**/*.{spec,test}.{ts,tsx}"],
    coverage: {
      provider: "v8",
      // The native bindings are generated by napi-rs into `index.js` /
      // `index.d.ts` at the repo root and are not authored TypeScript;
      // the tests themselves are the only first-party JS we ship, so we
      // measure coverage against the test surface instead.
      include: ["test/**/*.ts"],
      thresholds: {
        branches: 60,
        functions: 60,
        lines: 60,
        statements: 60,
      },
    },
  },
});
